-- MySQL Script generated by MySQL Workbench
-- Sun 24 Jan 2021 08:29:11 AM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_Recipe_Remote
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DB_Recipe_Remote` ;

-- -----------------------------------------------------
-- Schema DB_Recipe_Remote
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_Recipe_Remote` ;
USE `DB_Recipe_Remote` ;

-- -----------------------------------------------------
-- Table `DB_Recipe_Remote`.`RECIPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Recipe_Remote`.`RECIPE` ;

CREATE TABLE IF NOT EXISTS `DB_Recipe_Remote`.`RECIPE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `RName` VARCHAR(25) NOT NULL,
  `Author` VARCHAR(25) NULL,
  `Prep_Time` INT NULL,
  `Cook_Time` INT NULL,
  `Instructions` VARCHAR(500) NOT NULL,
  `Difficulty` VARCHAR(10) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Recipe_Remote`.`REC_CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Recipe_Remote`.`REC_CATEGORY` ;

CREATE TABLE IF NOT EXISTS `DB_Recipe_Remote`.`REC_CATEGORY` (
  `RID` INT NOT NULL,
  `Nationality` VARCHAR(45) NULL,
  `Is_Vegeterian` TINYINT NOT NULL,
  `Type` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`RID`),
  CONSTRAINT `fk_REC_CATEGORY_1`
    FOREIGN KEY (`RID`)
    REFERENCES `DB_Recipe_Remote`.`RECIPE` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Recipe_Remote`.`MEASURE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Recipe_Remote`.`MEASURE` ;

CREATE TABLE IF NOT EXISTS `DB_Recipe_Remote`.`MEASURE` (
  `MID` INT NOT NULL AUTO_INCREMENT,
  `Measure` VARCHAR(15) NULL,
  PRIMARY KEY (`MID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Recipe_Remote`.`FOOD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Recipe_Remote`.`FOOD` ;

CREATE TABLE IF NOT EXISTS `DB_Recipe_Remote`.`FOOD` (
  `FID` INT NOT NULL AUTO_INCREMENT,
  `FName` VARCHAR(25) NOT NULL,
  `FCalories` DECIMAL NULL,
  PRIMARY KEY (`FID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Recipe_Remote`.`REC_INGREDIENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Recipe_Remote`.`REC_INGREDIENT` ;

CREATE TABLE IF NOT EXISTS `DB_Recipe_Remote`.`REC_INGREDIENT` (
  `RIID` INT NOT NULL,
  `Food_ID` INT NOT NULL,
  `Measure_ID` INT NULL,
  `Amount` DECIMAL NOT NULL,
  INDEX `fk_REC_INGREDIENT_2_idx` (`Measure_ID` ASC) VISIBLE,
  INDEX `fk_REC_INGREDIENT_3_idx` (`Food_ID` ASC) VISIBLE,
  PRIMARY KEY (`RIID`, `Food_ID`),
  CONSTRAINT `fk_REC_INGREDIENT_1`
    FOREIGN KEY (`RIID`)
    REFERENCES `DB_Recipe_Remote`.`RECIPE` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_REC_INGREDIENT_2`
    FOREIGN KEY (`Measure_ID`)
    REFERENCES `DB_Recipe_Remote`.`MEASURE` (`MID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REC_INGREDIENT_3`
    FOREIGN KEY (`Food_ID`)
    REFERENCES `DB_Recipe_Remote`.`FOOD` (`FID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
